### ISSUE TITLE
failed to parse localhost:8080:80

### ISSUE THREAD

**Issue by isomorphisms** [saulpw/vdgalcon#8]
```
$ ./vdgalcon.py localhost:8080
Galactic Conquest for VisiData
player name: isomorphisms
password:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3.6/site-packages/urllib3/util/url.py", line 234, in parse_url
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: http://localhost:8080:80/auth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./vdgalcon.py", line 393, in <module>
    g_client.login()
  File "./vdgalcon.py", line 115, in login
    r = requests.post(self.server_url + '/auth', data=data)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 381, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://localhost:8080:80/auth
```

**Comment by saulpw** [comment]
Hi @isomorphisms, vdgalcon is a bit broken at the moment.  I'll push some changes I made recently to get it a bit more functional, but it needs some serious love. Maybe over the holidays I'll find some time and fix it up, and we can put together a game.
